### ISSUE TITLE
请问如何在文章中声明置顶

### ISSUE THREAD

**Issue by Yansera** [tangyuxian/hexo-theme-tangyuxian#15]
你好~~
谢谢po主开源模板

我有一些问题想要请教一下~
首先请问怎么在文章中声明这是置顶文章？

以及请问如何加入google scholar的social图标？

谢谢！

**Comment by Yansera** [comment]
置顶看源码找到啦！
在文章中加入top: true

图标也完成了！
打扰了！

**Comment by Yansera** [comment]
全部解决
打扰了~

**Comment by Yansera** [comment]
测试了一下 在文章中加入top: true只能增加一个标签的图案
不会让文章跑到最前面

**Comment by tangyuxian** [comment]
使用的是hexo-generator-index-pin-top插件哦

**Comment by Yansera** [comment]
好的~
谢谢回答~
