### ISSUE TITLE
请问Cannot read property 'data' of undefined是什么原因

### ISSUE THREAD

**Issue by wellcoming** [tangyuxian/hexo-theme-tangyuxian#7]
![image](https://user-images.githubusercontent.com/74850890/136571257-d9ca274a-7b88-4979-9c25-55f89aaa6279.png)
在hexo g的时候生成about页面和frenid页面，这两个页面的html文件是空的，上面是报错。

**Comment by tangyuxian** [comment]
应该是既没有自动匹配到封面也没有自定义封面.你看下about页面和friend页面是不是以下配置
friend.md文件头
---
title: 朋友
date: 2020-11-25 15:14:00
tags:
layout: py
---

about.md文件头
---
title: 关于
date: 2020-11-07 15:14:00
tags:
layout: about
permalink: about.html
cover: https://cdn.jsdelivr.net/gh/tangyuxian/blog_image@latest/background/xiaomai.jpg
coverWidth: 1200
coverHeight: 520
---

**Comment by wellcoming** [comment]
谢谢，完美解决。

**Comment by smurf-1119** [comment]
请问这是为什么？
![image](https://user-images.githubusercontent.com/63043716/151840494-20662887-758a-49e7-b318-469e0f82f579.png)

**Comment by wangwangit** [comment]
请问friend的md添加友链的格式是咋样的!有示例么?
