### ISSUE TITLE
请问ReferenceError是什么问题呀？

### ISSUE THREAD

**Issue by southner** [tangyuxian/hexo-theme-tangyuxian#9]
![图片](https://user-images.githubusercontent.com/44355949/167297996-ec16b070-a76c-4ae3-8952-d2b7afe62733.png)

**Comment by tangyuxian** [comment]
哦,没有安装字数统计插件哦 名字叫 hexo-wordcount   安装上就好啦

**Comment by southner** [comment]
好的，感谢！
